//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchTutorial.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchTutorial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким именем уже зарегистрирован.
        /// </summary>
        public static string ErrorAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string ErrorPasswords {
            get {
                return ResourceManager.GetString("ErrorPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль слишком короткий.
        /// </summary>
        public static string ErrorShortPassword {
            get {
                return ResourceManager.GetString("ErrorShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные пользователя не верны.
        /// </summary>
        public static string ErrorUserData {
            get {
                return ResourceManager.GetString("ErrorUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя имеет неверный формат.
        /// </summary>
        public static string ErrorUsername {
            get {
                return ResourceManager.GetString("ErrorUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсказка.
        /// </summary>
        public static string HintButton {
            get {
                return ResourceManager.GetString("HintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\Lessons.
        /// </summary>
        public static string PathLessons {
            get {
                return ResourceManager.GetString("PathLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\..\\Tests.
        /// </summary>
        public static string PathTests {
            get {
                return ResourceManager.GetString("PathTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация прошла успешно.
        /// </summary>
        public static string SuccessRegistration {
            get {
                return ResourceManager.GetString("SuccessRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string TitleAuthentication {
            get {
                return ResourceManager.GetString("TitleAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсказка.
        /// </summary>
        public static string TitleHint {
            get {
                return ResourceManager.GetString("TitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string TitleHistory {
            get {
                return ResourceManager.GetString("TitleHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Урок.
        /// </summary>
        public static string TitleLessonViewer {
            get {
                return ResourceManager.GetString("TitleLessonViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войди/зарегистрируйся.
        /// </summary>
        public static string TitleLoginPopup {
            get {
                return ResourceManager.GetString("TitleLoginPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главное меню.
        /// </summary>
        public static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string TitleRegistration {
            get {
                return ResourceManager.GetString("TitleRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестирование.
        /// </summary>
        public static string TitleTest {
            get {
                return ResourceManager.GetString("TitleTest", resourceCulture);
            }
        }
    }
}
